### ISSUE TITLE
[Question] Does it require jQuery 3.2.1?

### ISSUE THREAD

**Issue by wzol** [neuedaten/in-viewport-class#1]
It seems like a nice, compact library, but doesn't work for me - no errors. Is it because of the jQuery version - I'm still at 1.12.2?

**Comment by r12r** [comment]
Hi, I will try it later today with some older jQuery versions.

**Comment by r12r** [comment]
Hi @wzol. I have tested the script with your jquery version (1.12.2) and it work's fine!
Do you have used this file? `in-viewport-class/dist/jquery.in-viewport-class.js`

**Comment by wzol** [comment]
I've used this: `jquery.in-viewport-class.min.js` - should be the same, or no?

**Comment by r12r** [comment]
Should be. Maybe you can try the the new plain javascript version `dist/in-viewport-class.js`
Here you can find a working example: [https://www.neuedaten.de/in-viewport-class/](https://www.neuedaten.de/in-viewport-class/)

**Comment by wzol** [comment]
This one is working perfectly thank you! 👍 

One minor thing: when I load the page and some elements are already in the viewport, it seems that the script waits for the full page to load and then adds the classes - example if there are AdSense ads on the page, you can see that the animation only starts after the ad is fully loaded. It should be async, still, it seems like it makes the first check on document load and not document ready.

**Comment by r12r** [comment]
Thanks for the hint! I will check and optimize the loading process.

**Comment by wzol** [comment]
I did a slight change in the `dist/in-viewport-class.js`, and now it starts instantly (doesn't wait for ads):

replace:
`if (document.readyState === 'complete') {`
with
`if (document.readyState === 'interactive' || document.readyState === 'complete') {`
