### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by justanothersynth** [neuedaten/in-viewport-class#2]
Hey, I know this isn't an issue and that I'm angering the GitHub gods by writing this in the issue section, but I just really wanted to say that this little plugin is amazing, very well coded and very well thought-out :) Keep up the amazing work and thanks for sharing!!

NJ

**Comment by r12r** [comment]
Thank you! Feel free to give a star. 😀 
I would be really happy to see something that you built with this script.
